<!DOCTYPE head PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <?php 
  $this->headScript()->prependFile($this->baseUrl().'/library/jqueryValidation/jquery-validation.js');
    $this->headScript()->prependFile($this->baseUrl().'/library/bootstrap.3.1.1/js/bootstrap.js');
    $this->headScript()->prependFile($this->baseUrl().'/library/jquery/jquery-1.8.2.min.js');
 
    $this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap.3.1.1/css/bootstrap.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-custom/main.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/library/font-awesome-4.2.0/css/font-awesome.css');
    echo $this->headLink();
    echo $this->headScript();
    ?>
  <link rel="shortcut icon" href="<?php echo $this->baseUrl('/img/logo.ico');?>">
  <title>Recordatorios</title>
  <style type="text/css">
    body {
      padding-top: 50px;
    }
    .starter-template {
      padding: 40px 15px;
    }
  </style>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Topicos</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<?php echo $this->controller=="note"? 'active' : '' ?>">
                <a href="<?php echo $this->url(array('module' => 'client','controller' => 'note', 'action' => 'new'), null, true);?>">Nueva nota</a>
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url(array('module' => 'default','controller' => 'login', 'action' => 'logout'), null, true);?>"><i class="glyphicon glyphicon-lock"></i> Salir</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="starter-template">
        <?php echo $this->layout()->content?>
      </div>
    </div>
    
</body>
</html>