<!DOCTYPE head PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php
   // importar libreria bootstrap y jquery necesarios.
  ?>  
  <title>SmartBooking</title>

</head>
<body>
    <div class="header">
    <label>Menu de Layout</label>
     </div>

    <div class="container">
      <div class="starter-template">
        <?php echo $this->layout()->content?>
      </div>
    </div>
    
</body>
</html>