<!DOCTYPE head PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php 
    //$this->headScript()->appendFile($this->baseUrl().'/library/jquery/jquery-1.8.2.min.js');
    $this->headScript()->appendFile($this->baseUrl().'/library/bootstrap.3.1.1/js/bootstrap.js');
    $this->headScript()->prependFile($this->baseUrl().'/library/jqueryValidation/jquery-validation.js');
    $this->headScript()->prependFile($this->baseUrl().'/library/jquery/jquery-1.8.2.min.js');
    $this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap.3.1.1/css/bootstrap.css');
    $this->headScript()->appendFile($this->baseUrl().'/js/login/index.js');
    
    echo $this->headLink();
    echo $this->headScript();
  ?>
  <title>Topicos</title>
</head>
<body>
    <div class="container">
	    <div class="row" style="margin-top: 25px;">
			<div class="col-md-4 col-md-offset-4">
	    		<div class="panel panel-default">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Login</h3>
				 	</div>
				  	<div class="panel-body">
				    	<form id="form" action="" method="post" accept-charset="UTF-8" role="form">
	                    <fieldset>
				    	  	<div class="form-group">
				    		    <input class="form-control" placeholder="Usuario" id="username" name="username" type="text">
				    		</div>
				    		<div class="form-group">
				    			<input class="form-control" placeholder="Password" name="password" type="password" value="">
				    		</div>
				    		<?php 
				    			if(isset($this->error)):
				    		?>
				    			<div class="alert alert-danger">
				    				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				    				<?php echo $this->error;?>
				    			</div>
				    		<?php 
				    			endif;
				    		?>
				    		<input class="btn btn-lg btn-primary btn-block" type="submit" value="Login">
				    	</fieldset>
				      	</form>
				    </div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>