<?php echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SmartBooking</title>
  
	<?php

	?>
</head>
<body>
	<div id="header" style="background-color: #EEEEEE; height: 30px;">
		<div id="header-logo" style="float: left">
			<b>Pagina Principal</b>
		</div>
	</div>

	<div class="container">
		<?php echo $this->layout()->content?>
	</div>
</body>
</html>
