<?php 
 $this->headLink()->appendStylesheet($this->baseUrl('/css/index/index.css'));
 ?>
<div class="container">
		<div class="row">
			<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 1 </h1>
							<h3> Trabajo </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>The idea of creating something out of nothing has always generated a passion in my heart. This is what lead me to website development. I can literally create little worlds that hopefully thousands of people can see and even experience.</p>
						</div>
					</div>
				</div>
			</div>
    		<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 2 </h1>
							<h3> Escuela </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves. People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. 
							This empowers us to find beauty in places where others have not dared to look including inside ourselves.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 3 </h1>
							<h3> Trabajo </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. This empowers us to find beauty in places where others have not dared to look including inside ourselves.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 4 </h1>
							<h3> Escuela </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. This empowers us to find beauty in places where others have not dared to look including inside ourselves.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 5 </h1>
							<h3> Trabajo </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. This empowers us to find beauty in places where others have not dared to look including inside ourselves.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="[ col-sm-6 col-md-4 ]">
				<div class="[ info-card ]">
					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> Nota 6 </h1>
							<h3> Escuela </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>People often say that beauty is in the eye of the beholder, and I say that the most liberating thing about beauty is realizing that you are the beholder. This empowers us to find beauty in places where others have not dared to look including inside ourselves.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>