<?php 
 $this->headLink()->appendStylesheet($this->baseUrl('/css/index/index.css'));
 $this->headScript()->prependFile($this->baseUrl('/js/index/index.js'));
 
function formatDate($date){
        $m_names = Array("Enero", "Febrero", "Marzo",
        		"Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
        		"Octubre", "Noviembre", "Diciembre");
        $dateAux = explode(" ", $date);
        list($year, $month, $day) = explode("-", $dateAux[0]);
        $firstNumber = substr($month, 0, 1);
        $dateReturn = null;
        if($firstNumber == 0){
        	$dateReturn = $day."/".$m_names[substr($month, 1, 2)-1]."/".$year;
        }else{
        	$dateReturn = $day."/".$m_names[$month -1]."/".$year;
        }
    	return $dateReturn;
    }
 ?>
<div class="container">
		<div class="row">
		      <?php foreach ($this->notes as $note):?>
		          <div class="[ col-sm-6 col-md-4 ]">
    				<div class="[ info-card ]">
    					<img style="width: 100%" src="<?php echo $this->baseUrl('/img/nota.jpg');?>" />
    					<div class="[ info-card-details ] animate">
    						<div class="[ info-card-header ]">
    							<h1> <?php echo $note->getTitle();?> </h1>
    							<h3> <?php echo $note->getTypeNote()->getName();?> </h3>
    							<h4><?php echo formatDate($note->getDate());?></h4>
    						</div>
    						<div class="[ info-card-detail ]">
    							<!-- Description -->
    							<p><?php echo $note->getNote();?></p>
    						      <a onclick="confirmDeleteNote(<?php echo $note->getId();?>,'<?php echo $note->getTitle();?>')" class="btn btn-default pull-right" style="margin-right: 10px;">Eliminar</a>
    						      <a href="<?php echo $this->url(array('module'=>'client', 'controller' => 'note', 'action' => 'edit','id'=>$note->getId()));?>" class="btn btn-default pull-right" style="margin-right: 10px;">Editar</a>
    						</div>
    					</div>
    				</div>
    			</div>
		      <?php endforeach;?>
		</div>
	</div>
	
	    <div id="dialog-delete" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title">Eliminar Nota</h4>
	      </div>
	      <div class="modal-body">
	        <p>&iquest;Esta seguro que desea eliminar la nota <b id="nameNote"></b>?</p>
	      </div>
	      <form action="<?php echo $this->url(array('module'=>'client', 'controller' => 'note', 'action' => 'delete'),null,true);?>" method="post" class="form-horizontal" role="form">
	      <input type="hidden" id="idDelete" name="idDelete" value=""/>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        <button type="submit" class="btn btn-primary">Aceptar</button>
	      </div>
	      </form>
	      
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->