
        <div class="row">
            <div class="col-md-offset-1 col-md-11">
                <h1>Agregar recordatorio</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form id="form" action="#" method="post" class="form-horizontal" role="form">
                
                    <div class="form-group">
                      <label for="name" class="col-md-2 control-label">Titulo:</label>
                      <div class="col-md-3">
                        <input type="text" id="title" name="title" class="form-control" placeholder="Titulo"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="type" class="col-md-2 control-label"><span class="required">*</span> Tipo Nota:</label>
                                <div class="col-md-3">
                                    <select class="form-control" id="id_type" name="id_type" data-size="10" >
                                    <option value="">Tipo</option>
                                    </select>
                                </div>
                    </div>
                    
                    <div class="form-group">
                      <label for="priority" class="col-md-2 control-label"><span class="required">*</span> Prioridad:</label>
                                <div class="col-md-3">
                                    <select class="form-control" id="id_priority" name="id_priority" data-size="10" >
                                    <option value="">Prioridad</option>
                                    </select>
                                </div>
                    </div>
                    
                    <div class="form-group">
                       <label for="priority" class="col-md-2 control-label"><span class="required">*</span> Comentarios:</label>
                                <div class="col-md-3">
                                    <textarea rows="7" cols="60" id="comment" name="comment" placeholder="Comentarios" class="form-control" style="resize: none; border:1px solid #00B7DF;"></textarea>
                                </div>
                    </div>
                    <br> 
        
                    <div class="form-group">
                    <div class="col-md-offset-1 col-md-3">
                        <input type="submit" value="Aceptar" class="btn btn-primary pull-right" />
                        <a href="<?php echo $this->url(array('module'=>'client', 'controller' => 'index', 'action' => 'index'));?>" class="btn btn-default pull-right" style="margin-right: 10px;">Cancelar</a>
                    </div>
                  </div>
                    
                </form>
            </div>
        </div>




